### ISSUE TITLE
Get private IP addresses and Internal dns Hostnames for each ASG

### ISSUE THREAD

**Issue by joncolas** [Icinga/icingaweb2-module-aws#1]
It is possible retrieve each ip or internal dns of each AWS autoscaling group instance in order to create new hosts using ip instead ASGname ?

**Comment by Thomas-Gelf** [comment]
Hi @joncolas,

do you want to fetch single instances with internal IPs or load balancers with their DNS name? I'm not sure whether the API offers a way to directly retrieve LB IPs, but that could be solved with the DNS lookup property modifier in the Director itself.

Cheers,
Thomas

**Comment by joncolas** [comment]
Thanks for the reply! I Would prefer get internal IPs for each ASG members so i think it would be better import each instance ip address instead of loadbalancer DNS names.

Greetings!
Jon

**Comment by Thomas-Gelf** [comment]
Hi Jon,

could you please give the current master a try? I pushed a big fat change allowing you to choose whether to import Autoscaling Groups, EC2 Instances or Load Balancers. EC2 instances have their (optional) public/private IP/DNS pairs, Load Balancers their DNS name only. Director master got a new property modifier for DNS lookups that might help in combination with Load Balancers, as they usually have multiple A records.

Cheers,
Thomas

**Comment by joncolas** [comment]
Yeah! it has imported all instances in AWS with tag and ip. Works great. Thankyou very much Thomas :+1:

**Comment by Thomas-Gelf** [comment]
Glad to hear that, you're welcome :-)
