### ISSUE TITLE
set aws credentials in the webinterface

### ISSUE THREAD

**Issue by b0e** [Icinga/icingaweb2-module-aws#11]
Hi,

at the moment the AWS credentials are configured in the keys.ini in the file system. It would be nice to configure the credentials in the webinterface. 

Thanks, b0e

**Comment by gcommit** [comment]
Hi, any news here?

**Comment by thiagonache** [comment]
this is not a best practice in security. see https://github.com/Icinga/icingaweb2-module-aws/issues/20
