### ISSUE TITLE
Sync hosts based on the list of AWS accounts and AWS instances tags

### ISSUE THREAD

**Issue by d-zalewski** [Icinga/icingaweb2-module-aws#13]
It would be nice if director could sync based on the list of AWS accounts and AWS instances tags similar as done by https://github.com/wojciecholesiejuk/icinga2-aws-multi-account-instance-discovery

**Comment by mxhash** [comment]
Hi,

AWS account is currently a different import source. Import based on tags can be done with Black or White Property Modifier and is in the making of director: https://github.com/Icinga/icingaweb2-module-director/pull/1926

More can be found here: #2
