### ISSUE TITLE
Getting authentication errors

### ISSUE THREAD

**Issue by TryTryAgain** [Icinga/icingaweb2-module-aws#15]
Trace: 

Fatal error: Uncaught ErrorException: Undefined index: file in /usr/share/php/Icinga/Exception/IcingaException.php:77 Stack trace: #0 /usr/share/php/Icinga/Exception/IcingaException.php(77): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined index...', '/usr/share/php/...', 77, Array) #1 /usr/share/icingaweb2/application/controllers/ErrorController.php(87): Icinga\Exception\IcingaException::getConfidentialTraceAsString(Object(Aws\Ec2\Exception\Ec2Exception)) #2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\ErrorController->errorAction() #3 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('errorAction') #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response)) #5 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response) in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 332

## Expected Behavior
Check for changes should connect to the specified account and grab changes

## Current Behavior
Getting the error "Checking this Import Source failed" and subsequent "Authorization header or parameters are not formatted correctly." ...when adding the EC2 type as a source. And getting "The security token included in the request is invalid." ... when adding AutoScaling group as the source type. I've confirmed with `aws cli` that these keys do in fact work with read only.

The accounts are listed as Aws module import sources, but cannot be connected to.

## Steps to Reproduce (for bugs)
1. Installed the icingaweb2-module-aws
2. Extracted the https://github.com/aws/aws-sdk-php/releases/download/2.8.30/aws.zip into `library/vendors/aws/`
3. Created the `/etc/icingaweb2/modules/aws/keys.ini` in the same format as the example, using multiple accounts with the `arn:aws:iam::aws:policy/ReadOnlyAccess` policy attached to the user the API key info is using
4. I click "Check for changes" and get the described error.

## Context
Not able to use the module, can't connect/query the AWS account/s

## Your Environment
* Module version: aws 0.6.0
* Icinga Web 2 version and modules: IcingaWeb2 v2.5.1

Modules: 

aws | 0.6.0
businessprocess | 2.1.0
cube | 1.0.1
director | 1.4.3
doc | 2.5.1
fileshipper | 1.0.1
generictts | 2.0.0
graphite | 0.9.0
map | 1.0.4
monitoring | 2.5.1
toplevelview | 0.2.1

* Icinga 2 version:

icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.11.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Webserver, PHP versions:

Server version: Apache/2.4.6 (CentOS)

PHP 7.1.14 (cli) (built: Jan 31 2018 08:35:35) ( NTS )

**Comment by TryTryAgain** [comment]
I even just tried with my Admin (FullAccess) API credentials/keys and same errors.

**Comment by cbnorman** [comment]
did anyone work this out i seem to be getting at least a similar problem when triggering the import source

![image](https://user-images.githubusercontent.com/10809716/41863396-82b537bc-789e-11e8-9cd3-0ae724130341.png)

**Comment by cbnorman** [comment]
just to update i resolved my issue above by putting the aws skd in the correct location. now working with no issues

**Comment by TryTryAgain** [comment]
@cbnorman ... mind sharing what "correct" location, does that differ from the default?

**Comment by cbnorman** [comment]
@TryTryAgain from memory i think when i installed the sdk it installs to a system location /var/lib/library/vendors/aws or something like that. when i moved it to the folder inside this module it started working. if that doesn't work let me know and ill get the exact location tomorrow

**Comment by Strijd** [comment]
@cbnorman 
I'm experiencing the same issue here, can you please post the solution

**Comment by mxhash** [comment]
Hi,

exact, the issue needs to be present in the /vendor/aws directory inside the module. This file is explicit required in AwsClient.php:246:

```php
    protected function prepareAwsLibs()
    {
        require_once dirname(__DIR__) . '/vendor/aws/aws-autoloader.php';
    }
```

Regards,
Marius
