### ISSUE TITLE
Filters Expression in sync rule not working

### ISSUE THREAD

**Issue by joncolas** [Icinga/icingaweb2-module-aws#2]
Hello! We would like to use some filters in order to not import all hosts so when I tried to test filter expresion in sync rule nothing happens i think is not working.

![screenshot at 13-32-23](https://cloud.githubusercontent.com/assets/8049798/19111512/3b9b7752-8b00-11e6-9624-60a99738c29a.png)
After saving this change nothing happens
![screenshot at 13-32-36](https://cloud.githubusercontent.com/assets/8049798/19111522/4e933b24-8b00-11e6-9a6c-e11e78136684.png)

Very thankfull,
Jon

**Comment by joncolas** [comment]
I want to import all but that host name `sandbox-ci-dev`

**Comment by Thomas-Gelf** [comment]
What Director version are you using? 1.1.0 or a recent GIT master?

**Comment by Thomas-Gelf** [comment]
Oh... and I guess I got the problem... Changing the filter at that point would not purge as the current purge mechanism is pretty conservative as it considers only objects that vanished between the import run related to the last sync and the one related to the current sync at the source. Setting a filter in this place should still ignore sandbox-ci-dev, in case you manually delete that host it wouldn't be re-imported I guess. Just, it is not elected being a candidate for purge...

**Comment by mbassett** [comment]
I had a similar issue where I did a lowercase on one of the tags from EC2, and the only way it picked up the new modification was to spawn a new EC2 instance or delete an EC2 instance to get it to re-sync.  Otherwise it said everything was already sync'd even though the modification properties were different.

**Comment by mbassett** [comment]
Actually it is still not carrying the modified properties forward when i try to use them for group membership  (i'm getting  Tools & TOOLS & tools   all as different groups because my environment is horribly inconsistent)   when i look at the data that sync generated i see the tag.env lowercased, but when the sync job gets it it is unmodified.

**Comment by Thomas-Gelf** [comment]
And you're sure that you are **running** the Import (not just "Check for changes") **before** running the sync?

**Comment by mbassett** [comment]
Yes, and if i look at the history of the sync i see the env tag lowercase, but when i add 

property tags.env ->  groups, i get response back there is no group TOOLS.

**Comment by Thomas-Gelf** [comment]
Any chance you could show me some related screenshot (Import history, Sync property definition) or, in case there is no confidential data in it, a DB-dump? (but please do not add a dump here in public)

**Comment by mbassett** [comment]
![icinga1](https://cloud.githubusercontent.com/assets/2250654/19779847/b5f2686a-9c37-11e6-81c0-54086c624cae.png)

![icinga2](https://cloud.githubusercontent.com/assets/2250654/19779852/b84063ec-9c37-11e6-924e-58fbf923c8cd.png)

![icinga3](https://cloud.githubusercontent.com/assets/2250654/19779889/d6a3a498-9c37-11e6-8cf4-2591169702e4.png)

The screenshot for the history of the machine with env:TOOLS  cuts off the data before it shows env set in it, so i didn't include that one.

I tried to create a sync job that would just create all the groups from env & app tags, but that failed to create any groups at all, so I manually created the groups.  I have a group named tools, but it won't let me create another one named TOOLS
![icinga4](https://cloud.githubusercontent.com/assets/2250654/19779982/479c4fec-9c38-11e6-8b35-d98942bb90ae.png)

**Comment by Thomas-Gelf** [comment]
Oh, I see... while we fixed this for variable names, our object names are still case insensitive in the MySQL schema - PostgreSQL is probable fine. That's wrong. Could you please open a related issue at https://dev.icinga.org/projects/icingaweb2-module-director/issues asking for case sensitive object names? I have to reflect about this a little bit before implementing it. It shouldn't hurt, but it's impact is huge.

**Comment by mbassett** [comment]
What i don't understand is why it is not respecting the lowercasing I set in the Modify page.  

Or why the group creation failed either.  Can i get more verbose output on failed jobs?

This is always the error, even if i remove every host group that i manually created.

This Sync Rule failed when last checked at 2016-10-27 00:49:54: Trying to recreate icinga_hostgroup (common)

**Comment by Thomas-Gelf** [comment]
I pushed a related fix to the Director. While showing you those properties in the dropdown, it wasn't able to work with nested keys. Now it does. You'll  have to tell your transform definition to write the result to a dedicated column, a feature that is missing on your screenshot but in the master since quite some time. You could either [upgrade](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/05-Upgrading.md) to the current master or wait a week for the [next release](https://dev.icinga.org/projects/icingaweb2-module-director/roadmap).

Cheers,
Thomas

**Comment by mbassett** [comment]
I will upgrade to master and give it a shot.  Thanks for the quick responses :)

**Comment by mbassett** [comment]
Looks like a missing }  on master of director

Parse error: syntax error, unexpected 'public' (T_PUBLIC) in /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php on line 138
line 117 needs a }

**Comment by Thomas-Gelf** [comment]
Sorry for that, fixed it

**Comment by mbassett** [comment]
Is there an easy way to clear all hosts and hostgroups?

**Comment by Thomas-Gelf** [comment]
Not in the GUI. Quick and dirty:

`mysql director -e "DELETE FROM icinga_host WHERE object_type = 'object'; DELETE FROM icinga_host_group"
`

Foreign key constraints should take care about other related tables. But please note that this action will not show up in the activity log.

**Comment by mbassett** [comment]
it was icinga_hostgroup but thanks!

**Comment by mbassett** [comment]
Still getting that error trying to create groups

![icinga5](https://cloud.githubusercontent.com/assets/2250654/19783299/4b38d694-9c46-11e6-9347-1b09d73cc4d6.png)

**Comment by Thomas-Gelf** [comment]
Does your import source ship groups or do you have some kind of "host import", using that one to create hostgroups by a specific property? Or, asked differently: I guess your key column name in the import source is not related to your groups, is that correct?

In case my assumption is true, your problem is that you have multiple rows creating the same group again and again. This triggers this error, intentionally.

**Comment by mbassett** [comment]
The import source is just straight EC2.  it sets all the host names to the instance id's, and then i set the display_name to the tag.Name

Also doing the modification to lowercase on tag.app and tag.env

What i expected to happen by choosing host group as the end result was to end up with all instances with the  tag.env = production|Production|PRODUCTION in an icinga host group named production.

This is probably an issue with me not understanding exactly how this is supposed to work.

How do I accomplish this task with director?  I'd really prefer not to use an intermediary CMDB

**Comment by mbassett** [comment]
I can confirm your fixes seem to have worked.  I get the error now about nested fields, and was able to copy the data to a new field & have the lowercase modification work.

I still haven't found a way to automatically create the groups, but manually creating them they get placed in appropriate groups.  Thanks!

**Comment by joncolas** [comment]
Sorry for the delay, I would like to understand this better, and I have no way to do what is supposed to be done with synchronization rules. My goal is not to import hosts whose instance_id is `i-01a70d1a08f148d30`, I have a host with that name that has already been imported into icinga2, but it is always re-imported even deleting it from the director, so it seems that the rule doesnt do nothing.

I have it configured as shown in the image:

Once deleted the imported object `i-01a70d1a08f148d30`
![screenshot at 14-17-30](https://cloud.githubusercontent.com/assets/8049798/22021859/b744bd4e-dcbf-11e6-9450-733a27aa16f4.png)

and then the object is re-imported

![screenshot at 13-45-53](https://cloud.githubusercontent.com/assets/8049798/22021870/c5147676-dcbf-11e6-80cc-750f0f8516be.png)

Where should I set the Filter Expression if I do not want to import specific objects? better said, What settings do I need if I want to delete some hosts based on a filter and where to set the filter?

```
Director version -> 1.2.0
Aws module version -> 0.0.1
Icinga2 version -> r2.5.4-1
```

To finish, to thank you for all your work and effort in this.

**Comment by mbassett** [comment]
@joncolas I do not know why, but in my testing private_ip works while most of the other filters do not work.  Try using the machine's private_ip as a filter.  

Also, I would probably instead disable the node manually and then use the replace sync method so it will remain disabled forever.

**Comment by mbassett** [comment]
@joncolas I just looked again, and for your filter to work you want name=  not host=

Check the preview output on your import source for hints :)

**Comment by carlweise** [comment]
I am experiencing a similar issue when trying to filter on tags.Name as nested keys don't seem to be evaluated do you have any suggestions?

![screenshot from 2017-02-06 17-06-09](https://cloud.githubusercontent.com/assets/17063098/22657607/fcaf46fe-ec8e-11e6-8272-b8bf8f079c8b.png)

**Comment by mbassett** [comment]
I have yet to determine a way to use any of the tags in filters.

I have a PR in which I thought it worked, but it only updated the preview page and still the filters did not work.

The only filters that i know for sure work are:

name ( this is not tags.name, and ends up being the instance ID )
private_ip
image

**Comment by joncolas** [comment]
Ohh It has been a long time since the last time, I had to use the filter in 2 places, in the `Sync rule` and in the `Properties`. Due to I need map instance Tag.Name -> display_name  i had to define the same filter in `syn rule` and in `display_name` field for `sync rule properties`.

Location 1, Sync Rule > Modify > `Filter Expression`: `!(private_ip=|private_ip=172.16.*)`
Location 2, Sync Rule > Properties > Set `based on filter` : `Yes` and `Filter Expression` : `!(private_ip=|private_ip=172.*)`. As shown in the image

![screenshot at 11-44-06](https://user-images.githubusercontent.com/8049798/38082303-85b9ff76-3346-11e8-86a6-8b7cd16ec98b.png)


Thanks @mbassett and @Thomas-Gelf, I think this could be closed

**Comment by leegarrett** [comment]
I too would like to get this fixed (btw, the tooltip is a red herring: "host=foo" is not a valid filter, it has to be "name=foo").

Currently I'm using the following filter to do A/B testing:
```
aws_environment=*&(name=i-052137806d670f7bc|name=i-081f9c0ae0defeb96)
```
`i-052137806d670f7bc` has the AWS tag environment=production set, `i-081f9c0ae0defeb96` does not have such a tag set. Through the sync properties I'm mapping `${tags.environment}` to `aws_environment`. I can verify in the generated config that vars.aws_environment is set for the first machine, but not for the second. However, with the above filter *both* hosts are imported.

```
aws_environment=production&(name=i-052137806d670f7bc|name=i-081f9c0ae0defeb96)
```
With the above filter *no* hosts are imported, which makes me think that the filter syntax is completely broken, or not working as documented.

Is there an ETA on when this can get fixed? Right now the AWS module is of limited use with autoscaling groups where ec2 instances get provisioned on demand.

**Comment by mxhash** [comment]
Hi,

filtering should be done earlier and not only in the sync rule. Instead you can use a black or white property modifier to filter out things you don't need. But you can't access sub keys here. This is something director related: https://github.com/Icinga/icingaweb2-module-director/pull/1926

**Comment by mxhash** [comment]
<img width="915" alt="Screenshot 2019-08-16 at 09 03 59" src="https://user-images.githubusercontent.com/2128679/63149555-cc35f080-c004-11e9-9b60-7a301722507f.png">
