### ISSUE TITLE
Use AWS IAM role credentials

### ISSUE THREAD

**Issue by marek-obuchowicz** [Icinga/icingaweb2-module-aws#20]
Use AWS IAM role credentials

## Expected Behavior
If no AWS credentials are provided, module should use AWS IAM role attached to running instance for AWS API.

## Current Behavior
Using "pre-generated" AWS API keys is against AWS security guidelines. They recommend using AWS IAM instance role policy to grant those privileges. At the moment most AWS client libraries support this, but this icinga module forces user to enter hardcoded secrets.

## Possible Solution
Either add an option to select if IAM role should be used, or just fallback to IAM role if no credentials are configured (backward-compatible and convenient).

## Context
We are having audit issues as this icinga module uses bad practices and requires to use static API credentials.

**Comment by thiagonache** [comment]
I'm sure you guys know that the code change is very simple:
```
diff --git a/library/Aws/AwsClient.php b/library/Aws/AwsClient.php
index 95549f3..9cb0b44 100644
--- a/library/Aws/AwsClient.php
+++ b/library/Aws/AwsClient.php
@@ -224,7 +224,6 @@ class AwsClient
     {
         $params = array(
             'region'  => $this->region,
-            'credentials' => $this->key->getCredentials(),
         );
 
         $config = Config::module('aws');
```
The problem is that WebUI requires a key in order to add the module... for testing, I've added fake key and applied code change above and everything work.

**Comment by thiagonache** [comment]
@Thomas-Gelf can you take a look, please? https://github.com/Icinga/icingaweb2-module-aws/pull/28
