### ISSUE TITLE
import alb and nlbs

### ISSUE THREAD

**Issue by cbnorman** [Icinga/icingaweb2-module-aws#21]
Is it possible to sync application and network based load balancers. it seems the import is only pulling in the classic elastic load balancers?

**Comment by mzhaase** [comment]
This would require AWS PHP SDK version 3. Not sure how much work that would be.

**Comment by Thomas-Gelf** [comment]
Our [Installation and Configuration](https://github.com/Icinga/icingaweb2-module-aws/blob/master/doc/01-Installation-and-Configuration.md#requirements) documentation reads:

> This module needs the AWS PHP SDK v2. The newer v3 requires PHP 5.5, a version not available without 3rd party (or SCL) repositories on many Enterprise Linux distributions as of this writing. So to make life easier for many people we decided to work with the older SDK.

In the meantime we raised requirements for Icinga Web 2, so this wouldn't be an issue. We could eventually tag a v0.7.0 with the latest fixes/features to make those happy who are still running Director on PHP 5.4. And then we could switch the master to SDK 3 and prepare a v0.8.0.

**Comment by mzhaase** [comment]
It would be nice, a couple things that are supported only in v3 which would probably be helpful for a lot of people:

- ACM
- API Gateway
- Application Auto Scaling
- Cost Explorer
- ECR
- EKS
- Elastic Load Balancing V2
- IOT
- Lightsail
- MQ
- Shield
- WAF
