### ISSUE TITLE
Full import of instance tags

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-aws#23]
Hi,

When I use the current master of this module I can not only import Auto-Scaling-Groups but also Instances.

When I want to add customvariables from the data source by Sync Rule I can see some of the `tags` of the AWS instances but not all. It seems like automatically added tags like `tags:aws:cloudformation:logical-id` get imported but custom set tags are not.

Am I missing something or is the module just importing a certain set of tags?

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
Could you please share a preview of your import source? Or, even better, when running Director from the current master -> `icingacli director importsource fetch --id <id>` ([CLI - Import Sources](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/60-CLI.md#import-sources)).

Of course eventually anonymize your output.

**Comment by Thomas-Gelf** [comment]
Thanks for your screenshots. Just for the records, the proposed solution was to choose "Custom Expression" and use `${tags.Ambiente}` etc. This syntax is also what appears when you first select another tag and then switch to "Custom Expression". For performance reasons not all tags are shown, retrieving them would require us to iterate the whole Import.

**Comment by widhalmt** [comment]
Sorry that I couldn't upload the screenshots here. There are too many company details in them.

I seems like your solution is working. I'm sorry that I can't completly confirm that it's solved because there are lot's of peculiarities in this customer setup which make confirmation harder than normal. I'll close the issue and reopen it when it's really not working.

Thank you so much for your help. It's very appreciated like always!
