### ISSUE TITLE
Error when executing import using ${tags.Name} as source field in property for Sync rules

### ISSUE THREAD

**Issue by joncolas** [Icinga/icingaweb2-module-aws#3]
I have this error, the import is not performed by an error getting the tag name that I use for the destination field "display_name"

![screenshot at 10-43-31](https://cloud.githubusercontent.com/assets/8049798/19230749/8277ae8c-8ed6-11e6-9da7-30a6e46b121c.png)
![screenshot at 10-38-49](https://cloud.githubusercontent.com/assets/8049798/19230750/82a51750-8ed6-11e6-8d47-cb215857c2c4.png)

This happens when using this property on sync rules and there are some instances without tag with Value Name empty

![screenshot at 10-44-51](https://cloud.githubusercontent.com/assets/8049798/19230779/9c040404-8ed6-11e6-9c36-8276bc0ce0cb.png)

Any idea to avoid this? I'm not sure, but perhaps it can be assigned the tag.Name "undefined" for all those instances that do not have complete tag.name, what do you think?

Greetings and thanks for this tool :+1:

**Comment by joncolas** [comment]
I thought that this happened when the tag-**value** was not defined, however, problem comes when there is no tag-**key** "Name"

So, `Undefined Index: Tags` is produced by instances without tag-key "Name" and sometimes it happens when instances from autoscalingGroups scale in/out or when you create new instance without name.

I hope this helps

**Comment by Thomas-Gelf** [comment]
I pushed a fix for a related issue, could you please give this another try and let me know whether it works now?

**Comment by joncolas** [comment]
sorry for too late response. Yeah it fixed!
