### ISSUE TITLE
EC2 source not working undefined index RootDeviceName

### ISSUE THREAD

**Issue by mbassett** [Icinga/icingaweb2-module-aws#4]
AWS ALG & ELB sources seem to work fine, but EC2 source failing:

This Import Source failed when last checked at 2016-10-26 22:38:52: Undefined index: RootDeviceName

**Comment by Thomas-Gelf** [comment]
I pushed a fix for this, could you please give it another try?

**Comment by mbassett** [comment]
looking good,  I had commented out the RootDeviceName in my client.php but your fix is much better!

Now I believe i have the same issue as #2 :/

**Comment by Thomas-Gelf** [comment]
What Director version are you using? 1.1.0 or a recent GIT master?
