### ISSUE TITLE
Error When trying to clone an existing import source with modifiers

### ISSUE THREAD

**Issue by ninjakitteh69** [Icinga/icingaweb2-module-aws#45]
When trying to clone an existing import source into a new one that contains modifiers, it gives an error. The only thing it asks for when i clone it is the new name, which does successfully validate if you try to use an existing name. when using a unique name, it throws an error.

```
Uncaught Error: Call to a member function setProperties() on null in /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php:128
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(329): Icinga\Module\Director\Objects\ImportSource->setModifiers(Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObjectWithSettings.php(23): Icinga\Module\Director\Data\Db\DbObject->set('modifiers', Array)
#2 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(429): Icinga\Module\Director\Data\Db\DbObjectWithSettings->set('modifiers', Array)
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php(107): Icinga\Module\Director\Data\Db\DbObject->setProperties(Array)
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/CloneImportSourceForm.php(58): Icinga\Module\Director\Objects\ImportSource::import(Object(stdClass), Object(Icinga\Module\Director\Db))
#5 /usr/share/icingaweb2/
```

## Expected Behavior
On submission, it should clone the import source with all properties

## Current Behavior
throws the error above instead

## Steps to Reproduce (for bugs)

1.create a new import source (name irrelevant)
2. Create a new modifier with the following values:
- Property: tags.Name
- Target property: object_name
- Modifier: Combine multiple properties
- Pattern: ${tags.Name}-${name}
3. Clone the import source with a unique name to get the error above

## Context
This issue forces me to have to manually redo all my modifiers for each account  (EC2, RDS, ASG) and again for each region

## Your Environment

* Module version (System - About): 1.0.0
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`):  2.11.3-1
* Operating System and version: CentOS Linux release 7.8.2003 (Core)
* Webserver, PHP versions: aoache2 (httpd) php 7.1.30

**Comment by ninjakitteh69** [comment]
I see this has been fixed in a commit in the director module and schedule to be added in a future release so going to close this issue.
https://github.com/Icinga/icingaweb2-module-director/issues/2016

fixed in commit: https://github.com/Icinga/icingaweb2-module-director/commit/a7c21743b940313d4a0c2f8af01a00a623e86aee

**Comment by EmmaTinten** [comment]
When will this be included?

**Comment by ninjakitteh69** [comment]
> When will this be included?

no idea but check above (fixed in commit) and just edit the file on your icinga instance. thats what i did on the interim
