### ISSUE TITLE
return vpc_id if it is set 

### ISSUE THREAD

**Issue by mbassett** [Icinga/icingaweb2-module-aws#5]
I do not see any way of retrieving the vpc_id from EC2 instance data source

We are migrating all of our services into VPC's and I'd like to be able to use the vpc_id as the zone

**Comment by mbassett** [comment]
Added to Aws/ProvidedHook/Director/ImportSource.php    is that the only place needed?

**Comment by Thomas-Gelf** [comment]
And to the extractAttributes calls in Aws/AwsClient::extractAttributes, it's pretty easy. First array is for required option, import will fail when any is missing - second array is for optional ones, those that do not exist on every instance. Left key is the property name as it will be imported, right column is the AWS property name.

In case it works for you it would be cool if you could send me a pull request!

**Comment by mbassett** [comment]
it's weird, these values are available inside the sync job, but if you look at the import results, none of the variables have any data.  instead all the data is contained inside tags field.

this means I can't use any of the tag data from filters

![image](https://cloud.githubusercontent.com/assets/2250654/22570188/39f2c48e-e94f-11e6-8c6b-466b8aa35fa1.png)
