### ISSUE TITLE
Is there a way to merge ec2 imported instances with already defined icinga agents?

### ISSUE THREAD

**Issue by mbassett** [Icinga/icingaweb2-module-aws#9]
Each icinga agent that I setup uses the fqdn as the name in director, but hosts that come from the EC2 import have instanceID as the name.

This causes me to have an icinga01.blah node as well as a node i-asdfasfasfd  that are really the same node, but end up separate and duplicating checks.

I'd like to be able to combine the 2 records or associate them somehow, is this possible?  

do I need to start registering icinga agents/satellites by their instance id?   This seems like it would be problematic from a management standpoint (difficult to identify which node is which).  I currently set the tags.Name to the display_name and I have my EC2 import set to purge... I assume I would need to change it in order for the import to not rename display_name to the tags.Name, but I'm not sure this is the best approach.

I'm also setting command_endpoint based on the host profile(by zone) and may run into issue as an icinga agent should be its own command_endpoint.

**Comment by Thomas-Gelf** [comment]
Syncing tags.Name to object_name should work fine, just set the source column to "Custom expression" and use ${tags.Name}. It is also perfectly legal to combine multiple import sources in a single sync rule.

**Comment by mbassett** [comment]
Hmm, that would work except for cases when 2 instances have the same ${tags.Name}  since the object_name must be unique.

Tricksy...

**Comment by mbassett** [comment]
This is working for my agents, i set their cn to the instance-id and everything merges properly
